// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

namespace Occasus.SQLEFRepository.Models
{
    public partial class OccasusContext : DbContext
    {
        public OccasusContext(SQLEFSourceSettings sQLSettings)
        {
            SQLSettings = sQLSettings;
        }

        public OccasusContext(DbContextOptions<OccasusContext> options, SQLEFSourceSettings sQLSettings)
            : base(options)
        {
            SQLSettings = sQLSettings;
        }

        private readonly SQLEFSourceSettings SQLSettings;

        public virtual DbSet<Setting> Settings { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Setting>().ToTable(SQLSettings.TableName);
            modelBuilder.Entity<Setting>().Property(x => x.Key).HasColumnName(SQLSettings.KeyColumnName);
            modelBuilder.Entity<Setting>().Property(x => x.Value).HasColumnName(SQLSettings.ValueColumnName);
        }

    }
}