// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace Occasus.SQLEFRepository.Models
{
    public partial class Setting
    {
        [Key]
        [StringLength(800)]
        [Unicode(false)]
        public string Key { get; set; }
        [Required]
        public string Value { get; set; }
    }
}